pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/FundyLord/Sports-Image-Classification.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t sports-backend .'
            }
        }
    }
}