apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sports-ingress
spec:
  rules:
  - host: sports.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: sports-backend-service
            port:
              number: 8000
