apiVersion: v1
kind: Service
metadata:
  name: sports-backend-service
spec:
  type: ClusterIP
  selector:
    app: sports-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007
