apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/fundylord/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sat, 11 Apr 2026 22:09:43 IST
        provider: minikube.sigs.k8s.io
        version: v1.38.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
users:
- name: minikube
  user:
    client-certificate: /home/fundylord/.minikube/profiles/minikube/client.crt
    client-key: /home/fundylord/.minikube/profiles/minikube/client.key
